### ISSUE TITLE
walk_binding seems unnecessary according to the type annotations

### ISSUE THREAD

**Issue by tych0** [qtile/qtile#2393]
```
$ mypy --python-version=3.8 -p libqtile
libqtile/core/manager.py:1041: error: Left operand of 'and' is always true
# remove left operand test and we get:
$ mypy --python-version=3.8 -p libqtile
libqtile/core/manager.py:1046: error: If condition is always true
```

which means the whole function is a no-op since we return if that is true. seems like the type annotations are probably wrong at the very least, or this function doesn't do anything. Introduced in 16643034381c9c8ab95864905df09c8a46963c1a

/cc #2247 @ep12

**Comment by ep12** [comment]
I guess mypy assumes that the function is always called with arguments adhering to the specification, e.g. https://github.com/qtile/qtile/blob/48f7c5e499fed64913732896a5fdc65fa921d2e8/libqtile/core/manager.py#L1038-L1039
The first check in line 1041 is just a sanity check to ensure that the `ks` and `kmm` values are of the correct type: https://github.com/qtile/qtile/blob/48f7c5e499fed64913732896a5fdc65fa921d2e8/libqtile/core/manager.py#L1041-L1042
The condition in parens should always be true. If not, just return. Maybe an error could be risen here... Theoretically, it shouldn't even make a difference if those two lines were removed. But just in case the type isn't quite right, it is better to deal with it early rather than wait for cryptic messages like `TypeError: can only join an iterable` to plop up.

The second one in https://github.com/qtile/qtile/blob/48f7c5e499fed64913732896a5fdc65fa921d2e8/libqtile/core/manager.py#L1045-L1046
is less obvious to me. If we have a `KeyChord` object, the `modifiers` attribute is a list (as per configuration). So if we encounter a `KeyChord` inside the root `KeyChord` (that got its modifier and key translated to integers), then the condition should not be true.

Aside: How exactly did you run `mypy`? If I run it with the arguments you passed, I get `Success: no issues found in 141 source files`. With `--strict` I get a lot of messages, but not the ones you saw.

Another thing: run `qtile cmd-obj -o cmd -f display_kb`. If that function was a no-op, you'd only see a header and none of your key bindings should be printed.

**Comment by ep12** [comment]
Ah and by the way: Thanks to you I just spotted that running `qtile cmd-obj -o cmd -f display_kb` when in a key chord doesn't print all the key bindings but only the currently active ones and the corresponding children. I am not sure if that is an issue or a feature though. No matter what, it is separate from this one. Nevertheless: Do you think this should be dealt with? (Should I open an issue for that?)

**Comment by tych0** [comment]
> The first check in line 1041 is just a sanity check to ensure that the ks and kmm values are of the correct type

Let's remove it, given the type annotations. No sense in checking something twice.

> The second one in 

It's the second half of the condition in line 1041, not 1045.

> How exactly did you run mypy? If I run it with the arguments you passed, I get Success: no issues found in 141 source files

Probably related to version. I gave the args above, but my version is

```
$ mypy --version
mypy 0.782
```
> Nevertheless: Do you think this should be dealt with?

display_kb displays the keyboard bindings for all keys, seems like it should display it for all key chords as well, yes.

**Comment by ep12** [comment]
> > The first check in line 1041 is just a sanity check to ensure that the ks and kmm values are of the correct type
>
> Let's remove it, given the type annotations. No sense in checking something twice.

Fine with that, although a typing annotation is just that, not a check.

> > The second one in
>
> It's the second half of the condition in line 1041, not 1045.

Your output said line 1046?
> > How exactly did you run mypy? If I run it with the arguments you passed, I get Success: no issues found in 141 source files
> 
> Probably related to version. I gave the args above, but my version is

Mine is 0.812, that should be enough to explain the change in checking behaviour.

> > Nevertheless: Do you think this should be dealt with?
> 
> display_kb displays the keyboard bindings for all keys, seems like it should display it for all key chords as well, yes.

Okay, I'll open a new issue.
