### ISSUE TITLE
All windows are invisible on launch after updating to 0.18.1

### ISSUE THREAD

**Issue by AmitGolden** [qtile/qtile#2834]
# Issue description

After updating to 0.18.1, every time I launch a window it's invisible, until I minimize then unminimaize it. 

# Qtile version

0.18.1 (0b238eacc964669aac7e48761339543687277245)

# Stack traces

~/.local/share/qtile/qtile.log:
```
2021-09-29 00:37:54,045 ERROR libqtile core.py:_xpoll():L329 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 297, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 679, in handle_MapRequest
    self.qtile.manage(win)
  File "/usr/lib/python3.9/site-packages/libqtile/core/manager.py", line 576, in manage
    self.current_screen.group.add(win, focus=win.can_steal_focus)
  File "/usr/lib/python3.9/site-packages/libqtile/group.py", line 243, in add
    elif self.floating_layout.match(win):
  File "/usr/lib/python3.9/site-packages/libqtile/layout/floating.py", line 111, in match
    return any(win.match(rule) for rule in self.float_rules)
  File "/usr/lib/python3.9/site-packages/libqtile/layout/floating.py", line 111, in <genexpr>
    return any(win.match(rule) for rule in self.float_rules)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1526, in match
    return match.compare(self)
AttributeError: 'dict' object has no attribute 'compare'
2021-09-29 00:37:54,151 ERROR libqtile core.py:_xpoll():L329 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 297, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1648, in handle_ClientMessage
    self.group.focus(self)
  File "/usr/lib/python3.9/site-packages/libqtile/group.py", line 219, in focus
    layout.focus(win)
  File "/usr/lib/python3.9/site-packages/libqtile/layout/base.py", line 466, in focus
    self.clients.current_client = client
  File "/usr/lib/python3.9/site-packages/libqtile/layout/base.py", line 249, in current_client
    self._current_idx = self.clients.index(client)
ValueError: Window(name='kitty', wid=60817423) is not in list
2021-09-29 00:37:54,201 ERROR libqtile core.py:_xpoll():L329 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/core.py", line 297, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1677, in handle_PropertyNotify
    self.update_hints()
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 639, in update_hints
    if self.group.floating_layout.match(self):
  File "/usr/lib/python3.9/site-packages/libqtile/layout/floating.py", line 111, in match
    return any(win.match(rule) for rule in self.float_rules)
  File "/usr/lib/python3.9/site-packages/libqtile/layout/floating.py", line 111, in <genexpr>
    return any(win.match(rule) for rule in self.float_rules)
  File "/usr/lib/python3.9/site-packages/libqtile/backend/x11/window.py", line 1526, in match
    return match.compare(self)
AttributeError: 'dict' object has no attribute 'compare'
```

This error was reported after launched a kitty terminal window (which was also invisible)

# Configuration

[My Qtile config](https://github.com/AmitGolden/dotfiles/blob/main/.config/qtile/config.py)

**Comment by m-col** [comment]
Duplicate of https://github.com/qtile/qtile/issues/2827. Please follow that trail for a solution.

**Comment by elParaguayo** [comment]
It's a duplicate of way more than just that one...

**Comment by AmitGolden** [comment]
Thank you! Problem solved
