### ISSUE TITLE
Qtile 0.15.1 crashes when importing Client

### ISSUE THREAD

**Issue by marcoobaid** [qtile/qtile#1633]
Please do not ask general questions here! There are [community
contact](https://github.com/qtile/qtile#community) options for that.

# Issue description
The following line causes Qtile 0.15.1 to crash.  It worked fine in 0.14.2.

```
from libqtile.command import Client
```
[http://docs.qtile.org/en/latest/manual/commands/scripting.html#client-server-scripting-model](http://docs.qtile.org/en/latest/manual/commands/scripting.html#client-server-scripting-model
)
# Qtile version
0.15.1

# Stack traces

```  
File "/home/marco/.config/qtile/config.py", line 33, in <module>
from libqtile.command import lazy, client
ImportError: cannot import name 'client' from 'libqtile.command' (/usr/lib/python3.8/site-packages/libqtile/command.py)

```
# Configuration
```
import os
import re
import socket
import subprocess
from libqtile.config import Drag, Key, Screen, Group, Drag, Click, Rule
from libqtile.command import lazy, client
from libqtile import layout, bar, widget, hook
from libqtile.widget import Spacer

```

**Comment by tych0** [comment]
It's not clear to me how this worked before, since you need to capitalize
Client for even v0.14.2, but it looks like what you want has moved to
command_client.CommandClient

**Comment by marcoobaid** [comment]
Yes. It was "Client" which capital C. The posted trace was collected after trying both c and C. I will try command_client.CommandClient shortly.

**Comment by marcoobaid** [comment]
Ok, it is working now. Just to help others, here is the new syntax:

```
from libqtile.command_client import CommandClient
```

**Comment by zordsdavini** [comment]
needs to update http://docs.qtile.org/en/latest/manual/commands/scripting.html#client-server-scripting-model

**Comment by ramnes** [comment]
Closing in favor of #1409
