### ISSUE TITLE
reconfigure_screens crashes with AttributeError: 'Screen' object has no attribute 'group' after zero-output randr event

### ISSUE THREAD

**Issue by wowi42** [qtile/qtile#6041]
## Summary

`reconfigure_screens` crashes with `AttributeError: 'Screen' object has no attribute 'group'` after a randr reconfigure where the backend temporarily reports zero outputs.

## Traceback

```
ERROR libqtile hook.py:fire():L181 Error in hook screen_change
Traceback (most recent call last):
  File "libqtile/hook.py", line 176, in fire
    result = i(*args, **kwargs)
  File "libqtile/core/manager.py", line 524, in reconfigure_screens
    self._process_screens()
  File "libqtile/core/manager.py", line 449, in _process_screens
    current_groups = [s.group for s in self.screens]
                      ^^^^^^^
AttributeError: 'Screen' object has no attribute 'group'
```

## Root cause

Regression from c6330039 ("core: ensure there is at least one screen", fixes #5995).

1. When `get_output_info()` returns zero outputs (which happens transiently during randr reconfigures), the loop in `_process_screens` never runs, and the fallback appends a bare `Screen()` to `new_screens`:

   ```python
   # There needs to be at least one screen.
   if len(new_screens) == 0:
       new_screens.append(Screen())
   ```

2. `Screen.group` is never set in `Screen.__init__`. It is only an annotation (`libqtile/config.py:413`). It gets assigned inside the `_process_screens` loop (line 491, or via `_configure` -> `set_group`). Since the loop never ran for the fallback screen, it ends up in `self.screens` with no `group` attribute.

3. On the next `screen_change` event, `_process_screens` runs again and line 449 does `[s.group for s in self.screens]`, which hits the group-less screen and raises.

So the sequence is: one randr event with zero outputs (bare screen installed), then a second event when outputs come back (crash).

## Suggested fix

Two parts, both in `_process_screens`:

1. When there are no outputs, keep the existing screens instead of replacing them with a bare `Screen()`. Only fall back to a bare `Screen()` when there are no screens at all (first startup with zero outputs).
2. Make the `current_groups` read tolerant, so even a group-less screen recovers on the next pass: read `getattr(s, "group", None)` and treat `None` as "needs a group" (fall through to `get_available_group` / `add_autogen_group`).

Happy to send a PR with this fix plus a regression test if that sounds right.

## Version

Running qtile from master at c6330039. Python 3.14.
